import type { Metadata } from "next";
import "./globals.css"

export const metadata: Metadata = {
  title: {
    default : "Next js tutorial---Vivek Gupta" ,
    template : "%s | Prahalad Smart Classes.",
  },
  description: "Generated by Vivek Gupta",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <header
      style = {{
        backgroundColor: "lightblue",
        padding : "1rem",
      }}
      >
        <p> Header</p>
      </header>
        {children}
        <footer
         style = {{
        backgroundColor: "ghostWhite",
        padding : "1rem",
      }}
        >
          <p> Footer</p>
        </footer>
      </body>
    </html>
  );
}
